export const arrayProducts = [
  { descricao: 'Camiseta estampada', categoria: 'Roupas', valor: 29.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Calça jeans skinny', categoria: 'Roupas', valor: 49.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Tênis esportivo', categoria: 'Calçados', valor: 79.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Mochila urbana', categoria: 'Acessórios', valor: 39.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Relógio de pulso elegante', categoria: 'Acessórios', valor: 99.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Óculos de sol moderno', categoria: 'Acessórios', valor: 29.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Fone de ouvido sem fio', categoria: 'Tech', valor: 59.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Smartphone Android', categoria: 'Tech', valor: 299.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Tablet 10 polegadas', categoria: 'Tech', valor: 199.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Câmera digital compacta', categoria: 'Tech', valor: 149.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Livro best-seller', categoria: 'Livros', valor: 19.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Fone de ouvido com cancelamento de ruído', categoria: 'Tech', valor: 129.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Kit de ferramentas básicas', categoria: 'Utilitário', valor: 49.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Panela antiaderente', categoria: 'Utensílios', valor: 39.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Luminária de mesa', categoria: 'Decoração', valor: 24.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Jogo de lençóis de algodão', categoria: 'Cama', valor: 59.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Kit de maquiagem profissional', categoria: 'Beleza', valor: 89.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Bola de futebol oficial', categoria: 'Esportes', valor: 19.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Bicicleta urbana', categoria: 'Esportes', valor: 299.99, criado_por: 'Armazém de Ideias' },
  { descricao: 'Churrasqueira portátil', categoria: 'Churrasco', valor: 79.99, criado_por: 'Armazém de Ideias' }
];
